<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Data Tenaga Pendidik (Guru)</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }

        .header h2 {
            margin: 5px 0;
            font-size: 16px;
        }

        .header p {
            margin: 2px 0;
            font-size: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table th {
            background-color: #333;
            color: white;
            padding: 8px 4px;
            text-align: left;
            font-size: 9px;
        }

        table td {
            border: 1px solid #ddd;
            padding: 6px 4px;
            font-size: 8px;
        }

        table tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8px;
            color: #666;
        }

        .badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 8px;
            font-weight: bold;
        }

        .badge-success {
            background-color: #d4edda;
            color: #155724;
        }

        .badge-danger {
            background-color: #f8d7da;
            color: #721c24;
        }

        .badge-warning {
            background-color: #fff3cd;
            color: #856404;
        }
    </style>
</head>

<body>
    <div class="header">
        <h2>DATA TENAGA PENDIDIK (GURU)</h2>
        <p>Sistem Manajemen Sekolah</p>
        <p>Dicetak pada: {{ now()->format('d F Y, H:i') }} WIB</p>
        <p>Total Data: {{ $gurus->count() }} Guru</p>
    </div>

    <table>
        <thead>
            <tr>
                <th width="3%">No</th>
                <th width="12%">NIP</th>
                <th width="20%">Nama Lengkap</th>
                <th width="5%">L/P</th>
                <th width="12%">Status Kepegawaian</th>
                <th width="15%">Jabatan</th>
                <th width="20%">Mata Pelajaran</th>
                <th width="8%">Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($gurus as $index => $guru)
                <tr>
                    <td style="text-align: center;">{{ $index + 1 }}</td>
                    <td>{{ $guru->nip }}</td>
                    <td>{{ $guru->full_name }}</td>
                    <td style="text-align: center;">{{ $guru->jenis_kelamin }}</td>
                    <td>{{ $guru->status_kepegawaian }}</td>
                    <td>{{ $guru->jabatan ?? '-' }}</td>
                    <td>{{ is_array($guru->mata_pelajaran) ? implode(', ', $guru->mata_pelajaran) : $guru->mata_pelajaran }}
                    </td>
                    <td>
                        <span class="badge badge-{{ $guru->status_aktif === 'aktif' ? 'success' : 'danger' }}">
                            {{ ucfirst($guru->status_aktif) }}
                        </span>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" style="text-align: center;">Tidak ada data guru</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>© {{ date('Y') }} Sistem Manajemen Sekolah - Generated by IG to Web</p>
    </div>
</body>

</html>
