<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Data Barang Sarana & Prasarana</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }

        .header h2 {
            margin: 5px 0;
            font-size: 16px;
        }

        .header p {
            margin: 2px 0;
            font-size: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table th {
            background-color: #333;
            color: white;
            padding: 8px 4px;
            text-align: left;
            font-size: 9px;
        }

        table td {
            border: 1px solid #ddd;
            padding: 6px 4px;
            font-size: 8px;
        }

        table tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8px;
            color: #666;
        }

        .badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 8px;
            font-weight: bold;
        }

        .badge-success {
            background-color: #d4edda;
            color: #155724;
        }

        .badge-danger {
            background-color: #f8d7da;
            color: #721c24;
        }

        .badge-warning {
            background-color: #fff3cd;
            color: #856404;
        }

        .badge-info {
            background-color: #d1ecf1;
            color: #0c5460;
        }
    </style>
</head>

<body>
    <div class="header">
        <h2>DATA BARANG SARANA & PRASARANA</h2>
        <p>Sistem Manajemen Sekolah</p>
        <p>Dicetak pada: <?php echo e(now()->format('d F Y, H:i')); ?> WIB</p>
        <p>Total Data: <?php echo e($barangs->count()); ?> Barang</p>
    </div>

    <table>
        <thead>
            <tr>
                <th width="3%">No</th>
                <th width="12%">Kode Barang</th>
                <th width="25%">Nama Barang</th>
                <th width="15%">Kategori</th>
                <th width="15%">Ruang</th>
                <th width="8%">Jumlah</th>
                <th width="10%">Kondisi</th>
                <th width="12%">Status</th>
            </tr>
        </thead>
        <tbody>
            <?php $__empty_1 = true; $__currentLoopData = $barangs; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $index => $barang): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                <tr>
                    <td style="text-align: center;"><?php echo e($index + 1); ?></td>
                    <td><?php echo e($barang->kode_barang); ?></td>
                    <td><?php echo e($barang->nama_barang); ?></td>
                    <td><?php echo e($barang->kategori->nama ?? '-'); ?></td>
                    <td><?php echo e($barang->ruang->nama ?? '-'); ?></td>
                    <td style="text-align: center;"><?php echo e($barang->jumlah); ?></td>
                    <td>
                        <span
                            class="badge badge-<?php echo e($barang->kondisi === 'baik'
                                ? 'success'
                                : ($barang->kondisi === 'rusak_ringan'
                                    ? 'warning'
                                    : ($barang->kondisi === 'rusak_berat'
                                        ? 'danger'
                                        : 'info'))); ?>">
                            <?php echo e(ucwords(str_replace('_', ' ', $barang->kondisi))); ?>

                        </span>
                    </td>
                    <td>
                        <span
                            class="badge badge-<?php echo e($barang->status === 'tersedia' ? 'success' : ($barang->status === 'dipinjam' ? 'warning' : 'danger')); ?>">
                            <?php echo e(ucfirst($barang->status)); ?>

                        </span>
                    </td>
                </tr>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                <tr>
                    <td colspan="8" style="text-align: center;">Tidak ada data barang</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="footer">
        <p>© <?php echo e(date('Y')); ?> Sistem Manajemen Sekolah - Generated by IG to Web</p>
    </div>
</body>

</html>
<?php /**PATH E:\PROJEKU\telkom\resources\views\sarpras\barang-pdf.blade.php ENDPATH**/ ?>