<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Jadwal Pelajaran</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }

        .header h2 {
            margin: 5px 0;
            font-size: 16px;
        }

        .header p {
            margin: 2px 0;
            font-size: 10px;
        }

        .day-header {
            background-color: #4a5568;
            color: white;
            padding: 8px;
            margin-top: 15px;
            margin-bottom: 5px;
            font-weight: bold;
            font-size: 11px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }

        table th {
            background-color: #333;
            color: white;
            padding: 8px 4px;
            text-align: left;
            font-size: 9px;
        }

        table td {
            border: 1px solid #ddd;
            padding: 6px 4px;
            font-size: 8px;
        }

        table tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8px;
            color: #666;
        }

        .badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 8px;
            font-weight: bold;
        }

        .badge-success {
            background-color: #d4edda;
            color: #155724;
        }
    </style>
</head>

<body>
    <div class="header">
        <h2>JADWAL PELAJARAN</h2>
        <p>Sistem Manajemen Sekolah</p>
        <p>Dicetak pada: {{ now()->format('d F Y, H:i') }} WIB</p>
    </div>

    @php
        $hariOrder = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'];
        $totalJadwal = 0;
    @endphp

    @foreach ($hariOrder as $hari)
        @if (isset($jadwals[$hari]) && $jadwals[$hari]->count() > 0)
            <div class="day-header">{{ $hari }}</div>

            <table>
                <thead>
                    <tr>
                        <th width="5%">No</th>
                        <th width="20%">Mata Pelajaran</th>
                        <th width="20%">Guru Pengajar</th>
                        <th width="15%">Kelas</th>
                        <th width="15%">Waktu</th>
                        <th width="15%">Ruang</th>
                        <th width="10%">Status</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($jadwals[$hari] as $index => $jadwal)
                        @php $totalJadwal++; @endphp
                        <tr>
                            <td style="text-align: center;">{{ $index + 1 }}</td>
                            <td>{{ $jadwal->mataPelajaran->nama ?? '-' }}</td>
                            <td>{{ $jadwal->guru->full_name ?? '-' }}</td>
                            <td>{{ $jadwal->kelas->nama ?? '-' }}</td>
                            <td>{{ $jadwal->jam_mulai ? substr($jadwal->jam_mulai, 0, 5) : '-' }} -
                                {{ $jadwal->jam_selesai ? substr($jadwal->jam_selesai, 0, 5) : '-' }}</td>
                            <td>{{ $jadwal->ruang ?? '-' }}</td>
                            <td>
                                <span class="badge badge-success">
                                    {{ ucfirst($jadwal->status) }}
                                </span>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif
    @endforeach

    @if ($totalJadwal === 0)
        <p style="text-align: center; padding: 20px; font-size: 12px; color: #666;">
            Tidak ada jadwal pelajaran tersedia
        </p>
    @endif

    <div class="footer">
        <p>© {{ date('Y') }} Sistem Manajemen Sekolah - Generated by IG to Web | Total Jadwal: {{ $totalJadwal }}
        </p>
    </div>
</body>

</html>
